In [1]:
import numpy as np
array1=np.array([3,5,6,7,8,9])
print(array1)
print(type(array1))


[3 5 6 7 8 9]
<class 'numpy.ndarray'>


In [2]:
x=[[1,2,3],[4,5,6],[7,8,9,]]



In [3]:
ar=np.array(x)

In [4]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
ar.sum(axis=0)

array([12, 15, 18])

In [6]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [7]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [9]:
ar.ndim

2

In [10]:
one=np.array([1,3,555,53,3])

In [11]:
one.argmax()

2

In [12]:
one.argmin()

0

In [13]:
one.argsort()

array([0, 1, 4, 3, 2], dtype=int64)

In [14]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [17]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ar2=np.array([[1, 8, 3],
       [4, 5, 7],
       [2, 5, 9]])

In [19]:
ar*ar2

array([[ 1, 16,  9],
       [16, 25, 42],
       [14, 40, 81]])

In [20]:
ar+ar2

array([[ 2, 10,  6],
       [ 8, 10, 13],
       [ 9, 13, 18]])

In [21]:
np.sqrt(ar2)

array([[1.        , 2.82842712, 1.73205081],
       [2.        , 2.23606798, 2.64575131],
       [1.41421356, 2.23606798, 3.        ]])